### ISSUE TITLE
Requirements issues on Unix systems

### ISSUE THREAD

**Issue by Leofltt** [TheSoundOfAIOSR/rg_sound_generation#21]
Pywin32 and pywinty are not available on Unix systems. Are you guys going to provide a docker to run your submodule? OR are the requirements still not finalized?

**Comment by am1tyadav** [comment]
> 
> 
> Pywin32 and pywinty are not available on Unix systems. Are you guys going to provide a docker to run your submodule? OR are the requirements still not finalized?

Ah you're right, they are automatically pulled by streamlit depending on the OS. I've updated the requirements.txt now - let me know if everything works on Unix

**Comment by am1tyadav** [comment]
Hey @Leofltt closing this as the new requirements.txt should work on both win and unix, let me know if you still see an issue

**Comment by Leofltt** [comment]
Cool, I will test it tonight and let you know if anything pops up
